-- Migration 60: Ficha Cadastral e Dados Bancarios do Colaborador
ALTER TABLE public.colaboradores 
ADD COLUMN IF NOT EXISTS cpf TEXT,
ADD COLUMN IF NOT EXISTS rg TEXT,
ADD COLUMN IF NOT EXISTS data_nascimento DATE,
ADD COLUMN IF NOT EXISTS telefone TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS endereco TEXT,
ADD COLUMN IF NOT EXISTS pix_tipo TEXT,
ADD COLUMN IF NOT EXISTS pix_chave TEXT,
ADD COLUMN IF NOT EXISTS banco_nome TEXT,
ADD COLUMN IF NOT EXISTS banco_agencia TEXT,
ADD COLUMN IF NOT EXISTS banco_conta TEXT,
ADD COLUMN IF NOT EXISTS linha_onibus TEXT,
ADD COLUMN IF NOT EXISTS valor_passagem NUMERIC(12,2) DEFAULT 6.25;
